# -*- coding: utf-8 -*-
"""Histogram_plot

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qsj8rtk8HpYyPOrL7_FyiutxllV0j4_P
"""

import pandas as pd
from matplotlib import pyplot as plt

df = pd.read_csv("survey_results_public.csv")
df

df.columns

df['Age']

df.dropna(inplace=True)
df

df['Country']

male=df[df.Gender=="Man"].shape[0]
female=df[df.Gender=="Woman"].shape[0]
a=[male,female]
b=['Man','Woman']
plt.title('Pie Chart For Male And Female taken part in survey')
plt.pie(a,labels=b,colors=['yellow','red'],autopct='%.1f%%',shadow=True)
plt.show()

df.dropna(inplace=True)

df

df.groupby('Age1stCode').count().plot(kind='bar')

