# -*- coding: utf-8 -*-
"""Copy of pandasassigment1_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mRI-EJ9kkl2qYchAhS0Sqfa1pOmXh0ma
"""

#import required libraries
import pandas as pd

#load  data from imdb_1000.csv into dataframe and display it
from google.colab import files
data_to_load = files.upload()
import io
df = pd.read_csv(io.BytesIO(data_to_load['imdb_1000.csv']))
print(df)

#display info about dataframe
df.info()

#describe dataframe
df.describe()

#display first 10 rows from dataframe
result = df.head(10)
print("First 10 rows of the DataFrame:")
print(result)

#display last 10 rows from dataframe object
df = df.tail()
print("Last 10 rows of the Dataframe : ")
print(df)

# display rows from 100 index to 200 only
pd.DataFrame(df, index=[100, 200], columns=['star_rating', 'title', 'content_rating', 'genre', 'duration', 'actors_list'])

#change bydefauly index to title(title as row label)
df = df.rename(columns = {"star_rating	content_rating	genre	duration	actors_list":"title"}) 
df

#display rows from label 'The Dark Knight' to 'X-Men' by using loc
rows = df.loc["The Dark Knight":"X-Men"] 
print(rows)

#display all rows with star_rating greater than 7
print("display all rows with star_rating greater than 7:")
print(df[(df['star_rating'] > 7)])

#display all rows with star_rating greater than 7 and less than 9
print("display all rows with star_rating greater than 7 and less than 9:")
print(df[(df['star_rating'] < 9) & (df['star_rating'] > 7)])

#display all rows with genre==Crime
df.where(df['genre']=='Crime')

#count all rows with genre==Crime
df['genre'].value_counts()

#select all rows with duration >100
print("display all rows with duration >100:")
print(df[(df['duration'] > 100)])