# -*- coding: utf-8 -*-
"""pie_chart2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hBCMFA4ceNiErduw7R-apyUAJ3vp9-t-
"""

import pandas as pd
from matplotlib import pyplot as plt

df = pd.read_csv("computer_parts.csv")
df

plt.pie(NumberOfBugs,labels=ProductName,colors=['red','green','pink','orange','blue'])

a=df['Number Of Bugs'].values

b=df['Product Name;'].values

plt.pie(a,labels=b,colors=['red','green','pink','orange','blue'])
plt.legend(b)

shrikant = df.groupby(df["Product Name;"])["Number Of Bugs"].sum()
plt.pie(shrikant, labels=sums.index,autopct='%.1f%%')
plt.title("Computer_Parts")

