# -*- coding: utf-8 -*-
"""pie_chart.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iI4yz25IswS6QzNIapH5mB2oGTvEPz3B
"""

import pandas as pd
from matplotlib import pyplot as plt

df = pd.read_csv("dataset.csv")
df

a = df['gold_medal'].values
b = df['country'].values

a

b

plt.axis('equal')
plt.pie(a,labels=b,colors=['red','yellow'],autopct='%.1f')

plt.axis('equal')
plt.pie(a,labels=b,colors=['red','yellow','green','blue','cyan'],autopct='%.2f',explode=arr,shadow=True)
arr=[0,0,1,0,0]
plt.legend(b)

plt.axis('equal')
plt.pie(a,labels=b,colors=['red','yellow'],autopct='%.1f',explode=arr)
arr=[0,0,0,1,0]

plt.axis('equal')
plt.pie(a,labels=b,colors=['red','yellow','green','blue','cyan'],autopct='%.2f',explode=arr,shadow=True)
arr=[0,0,1,0,0]

